### ISSUE TITLE
Github Enterprise has no request headers

### ISSUE THREAD

**Issue by log0ymxm** [jupyter/nbviewer#389]
Not exactly sure on this, but when using nbviewer from the docker image there is an error attempting to access the X-RateLimit-Limit header,

```bash
[E 150109 17:22:15 ioloop:585] Exception in callback <function log_callback at 0x7f63b3db3050>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/curl_httpclient.py", line 255, in _finish
        time_info=time_info))
      File "nbviewer/client.py", line 32, in log_callback
        callback(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 242, in handle_response
        future.set_exception(response.error)
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 150, in set_exception
        self._set_done()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 177, in _set_done
        cb(self)
      File "nbviewer/github.py", line 72, in _log_rate_limit
        limit_s = r.headers.get('X-RateLimit-Limit', '')
    AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by log0ymxm** [comment]
My mistake, I had invalid credentials.
