### ISSUE TITLE
Running docker container fails

### ISSUE THREAD

**Issue by mpelko** [jupyter/nbviewer#424]
Following:

    $ docker pull jupyter/nbviewer
    $ docker run -p 8080:8080 jupyter/nbviewer

I get:

    Traceback (most recent call last):
    File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
      "__main__", fname, loader, pkg_name)
    File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
      exec code in run_globals
    File "/srv/nbviewer/nbviewer/__main__.py", line 2, in <module>
      main()
    File "nbviewer/app.py", line 175, in main
      frontpage_sections = json.load(f)
    File "/usr/lib/python2.7/json/__init__.py", line 290, in load
      **kw)
    File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
      obj, end = self.scan_once(s, idx)
      ValueError: Expecting ',' delimiter: line 50 column 7 (char 1566)

**Comment by bollwyvl** [comment]
Thanks, will definitely look into this!

Presumably, the frontpage json is not valid, and we should probably test
for that.

**Comment by dennisobrien** [comment]
The same issue also occurs when running locally.  I manually patched my local version since there is already a PR for this.

I like the idea of tests for well-formed json.  Nice work @bollwyvl

**Comment by bollwyvl** [comment]
haven't merged the tests, but this should be good now!
