### ISSUE TITLE
docker build fails at `invoke less`

### ISSUE THREAD

**Issue by ChristianKniep** [jupyter/nbviewer#616]
Hey there,

when I build your image I get the following error:

```
Step 18 : RUN invoke less
 ---> Running in 717bb57270f8
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/invoke/tasks.py", line 141, in argspec
    context_arg = arg_names.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.4/dist-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/usr/local/lib/python3.4/dist-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/usr/local/lib/python3.4/dist-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/local/lib/python3.4/dist-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/srv/nbviewer/tasks.py", line 29, in <module>
    @invoke.task
  File "/usr/local/lib/python3.4/dist-packages/invoke/tasks.py", line 267, in task
    return Task(args[0], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python3.4/dist-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python3.4/dist-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
The command '/bin/sh -c invoke less' returned a non-zero code: 1
>> Build failed...
```

Any idea how to overcome this?

Cheers
Christian

**Comment by bollwyvl** [comment]
Very odd. Looking into this now!

**Comment by bollwyvl** [comment]
Closing! Thanks @ChristianKniep! Give it a shot now, and reopen/start a new one if something is still lacking! I would like us to investigate testing the docker install more explicitly, perhaps as a matrix build... but perhaps it's really our lack of specificity on for reproducible build versions that caused the underlying issue. A new PR would have found it.
