### ISSUE TITLE
Deploying jupyter/nbviewer:latest to nbviewer.jupyter.org fails

### ISSUE THREAD

**Issue by parente** [jupyter/nbviewer#852]
Just tried to deploy latest from master HEAD and hit the above exception. 

```
[I 190907 22:32:17 app:154] Using plain memcache
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/nbviewer/nbviewer/__main__.py", line 2, in <module>
    main()
  File "/srv/nbviewer/nbviewer/app.py", line 396, in main
    nbviewer = NBViewer()
  File "/srv/nbviewer/nbviewer/app.py", line 329, in __init__
    self.init_tornado_application()
  File "/srv/nbviewer/nbviewer/app.py", line 280, in init_tornado_application
    cache=self.cache,
  File "/srv/nbviewer/nbviewer/app.py", line 156, in cache
    cache = AsyncMultiPartMemcache(memcache_urls.split(','), **kwargs)
NameError: name 'AsyncMultiPartMemcache' is not defined
```

@krinsman I'm looking to rollback the deployed and why the name is not defined. It seems related to the refactor but perhaps not.

**Comment by parente** [comment]
I've rolled back to the last working version for the time being: `jupyter/nbviewer@sha256:7159ee9172181e8de341c622db2c3f0b8b7f973a9859c1d42105ec81592e3694`

**Comment by parente** [comment]
Ugh. It's a capitalization mismatch (`P` vs `p`) and I had VSCode search configured for case insensitive search so that took way longer than it should have to track down.
