### ISSUE TITLE
nbviewer does not flush cache

### ISSUE THREAD

**Issue by shinokada** [jupyter/nbviewer#914]
Following the [FAQ](https://nbviewer.jupyter.org/faq#why-is-nbviewer-showing-an-outdated-version-of-my-notebook), I added `?flush_cache=true` at the end of my [URL](https://nbviewer.jupyter.org/github/shinokada/covid-19-stats/blob/master/covid-19-plotly.ipynb?flush_cache=true). I tried it, I waited for more than 10min, etc, but none of them worked. The nbviewer shows an outdated version of my notebook.

Any idea why this does not work?

**Comment by bryevdv** [comment]
I am having the same issue with the Bokeh notebooks. I have updated them for a new version of Bokeh and made a few other small changes. I can confirm the changes are in the raw files on GitHub. But nbviewer.org does not reflect these changes even with a `?flush_cache=true` and even though it states the page was rendered "a few seconds ago" I have also tried force-reloads, etc. but cannot get the new content to appear.

**Comment by bryevdv** [comment]
Seem to be having a similar issue with Bokeh notebooks. I updated the saved notebooks for a new Bokeh release and also made other small changes. I have confirmed the changes present in the raw files on GitHub. But no amount of `?flush_cache=true` makes the new content show up, despite the page stating that it was re-rendered "a few seconds ago" I have also cleared cache, force reloded, etc. 

https://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/quickstart/quickstart.ipynb

**Comment by bryevdv** [comment]
@minrk do you have any thoughts? Is there something we can try or check on on our end?

**Comment by ndricca** [comment]
Hi, I am experiencing the same issue on both the ipynb and the [html](https://nbviewer.jupyter.org/github/ndricca/covid-pollution-effect/blob/master/notebooks/covid_effect_pollution_milan.html?flush_cache=true) version of the same notebook. Nbviewer seems to keep a cache version corresponding to yesterday's version.

**Comment by betatim** [comment]
<img width="1031" alt="Screenshot 2020-04-01 at 23 14 55" src="https://user-images.githubusercontent.com/1448859/78187410-9f88f900-746e-11ea-9a3e-02e56d8def32.png">

This is what I see in the footer at 23:15, 1 April 2020 Zurich time. It seems like nbviewer thinks it re-rendered the notebook recently but the contents is old. Not sure where this points us but maybe it helps someone.

**Comment by betatim** [comment]
If i grep for `bokeh` in the nbviewer server logs while refreshing (with cache disabled) the quickstart notebook I see no log lines. This means (I think) that the response is being served from the CDN.

There is an exception printed in the logs. Seems to happen "every other" request, but not always. 
```
[E 200401 21:26:11 base_events:1615] Exception in callback _HandlerDelegate.execute.<locals>.<lambda>(<Task finishe...visibility'")>) at /usr/local/lib/python3.7/site-packages/tornado/web.py:2333
    handle: <Handle _HandlerDelegate.execute.<locals>.<lambda>(<Task finishe...visibility'")>) at /usr/local/lib/python3.7/site-packages/tornado/web.py:2333>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/newrelic/common/async_proxy.py", line 91, in send
        return self.__wrapped__.send(value)
    StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 2333, in <lambda>
        fut.add_done_callback(lambda f: f.result())
      File "/usr/local/lib/python3.7/site-packages/newrelic/common/async_proxy.py", line 91, in send
        return self.__wrapped__.send(value)
      File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/framework_tornado.py", line 419, in __exit__
        trace_cache().record_event_loop_wait(start_time, time.time())
      File "/usr/local/lib/python3.7/site-packages/newrelic/core/trace_cache.py", line 255, in record_event_loop_wait
        settings = transaction.settings.event_loop_visibility
    AttributeError: 'NoneType' object has no attribute 'event_loop_visibility'
```
I have no idea really what it is trying to tell us or how it fits into the nbviewer architecture.

**Comment by krinsman** [comment]
Have you all tried setting `flush_cache=false`? 

I've mentioned this in another thread, but I think the Boolean might be mixed up for the flush_cache query argument. 

See here: https://github.com/jupyter/nbviewer/issues/295#issuecomment-591660582

**Comment by bryevdv** [comment]
@krinsman that has no effect for me either.  Page updates to say "Rendered a few seconds ago" but the actual rendered notebook content does not update.

**Comment by krinsman** [comment]
Is this a notebook rendered on GitHub?

It might be an issue with the GitHub API's cache then (assuming the GitHub API caches things) -- cf. https://github.com/jupyter/nbviewer/issues/912

**Comment by bryevdv** [comment]
> Is this a notebook rendered on GitHub?

I don't understand the question. GitHub tries to render every notebook uploaded anywhere. In any case I link the notebook on GH above and you can see the rendered version GH shows the expected changes.

**Comment by krinsman** [comment]
GitHub website isn't the same as the GitHub API. Sometimes the API does not immediately pick up changes to the website, to the best of my knowledge.

**Comment by bryevdv** [comment]
The changes show up in GH raw view, and it's been four days (in the past updating nbviewer was never an issue, and never took more than an hour, much less a day). I think it's a stretch.

**Comment by krinsman** [comment]
Are we still talking about the notebook mentioned in this https://github.com/jupyter/nbviewer/issues/914#issuecomment-605736733 ?

**Comment by bryevdv** [comment]
Yes, that is the one I am referring to.

**Comment by krinsman** [comment]
OK yes, you're right, this is bizarre.

Another reason why it does not seem like it can be a GitHub API issue is that, when one clicks the "Download notebook link" from the NBViewer page, the raw .ipynb JSON one downloads is identical the one hosted on GitHub -- so the GitHub API is downloading the right JSON, it would just seem that NBViewer is displaying a different JSON for some reason.

The only possible reason (at present) I can imagine why this might be happening is because this is one of the notebooks on the frontpage, and perhaps something with the deployment (which I am not familiar with) somehow makes the caching on the frontpage different. (I.e. this issue might not occur for notebooks which are not on the NBViewer frontpage.)

In any case, the frontpage needs to be updated anyway (e.g. the Plotly notebook no longer exists, and the Lightning project is defunct, and there are no examples of notebooks written using R, and only one example using Julia, despite the project being JuPyteR), so optimistically I imagine that, if the frontpage of the website has a separate cache than the rest of the application in the deployment, somehow, then if/whenever the frontpage is updated hopefully this issue will go away for the Bokeh notebook.

Ultimately though I have to admit that I am baffled by this and do not know what the issue is.

**Comment by bryevdv** [comment]
Thanks for looking in to it!

**Comment by Robbberto** [comment]
I have the exact same issue. I uploaded a new version on Github and it's been days but the Nbviewer still did not update. I also tried the `?flush_cache=true` thing but still nothing happens. 
Does anyone know why this is happening?

This is the link of my notebook for reference:
https://nbviewer.jupyter.org/github/Robbberto/covid/blob/master/Covid.ipynb

**Comment by Robbberto** [comment]
As a test, I tried to delete the file from the github repo, and nbviewer is still showing the notebook!

**Comment by artur-deluca** [comment]
> As a test, I tried to delete the file from the github repo, and nbviewer is still showing the notebook!

Same here, I've deleted the rendered file and uploaded an updated version with a different name. nbviewer not only renders the deleted file but it doesn't find the new one.

**Comment by aakhmetz** [comment]
I have exactly the same problem as described by @artur-deluca - old version was persistent (flush cash did not work). When I rename my notebook I got the message: "Remote HTTP 404: scripts/XXX.ipynb not found among 16 files" similar to #916

**Comment by visualisedatadevelopment** [comment]
I am also having the same issue: nbviewer is still displaying old versions even when I append `?flush_cache=true` to the url.

**Comment by marcelfg** [comment]
I am also having the same issue. For now I am manually pointing my links in each update. I'm using the link generated by github to the nbviewer in the .ipynb file page.

![Captura de tela de 2020-05-15 19-00-20](https://user-images.githubusercontent.com/63625553/82100040-291f1e00-96df-11ea-917e-3b784762d0e5.png)

**Comment by minrk** [comment]
Sorry for being offline for a long time. I've looked into this and changed some caching configuration. We have too many caching layers that are semi-opaque (fastly and cloudflare), but I believe this should be fixed. We may see an increase in rate-limit consumption on nbviewer, though.

**Comment by sreekanthac** [comment]
Hello, this is issue still persists. Any work around available?

**Comment by NielsKlaver** [comment]
I had the same problem but was able to fix it with cleaning browser cache/history.

**Comment by onastov** [comment]
I am having the same issue with notebooks hosted on my personal website. 

- It works only when I append ?flush_cache=false to the url
- Both appending ?flush_cache=true and appending nothing give me the old version
- Cleaning browser cache/history does not help

**Comment by krinsman** [comment]
@onastov You're right, I think there is an error in the code where the behavior intended with `flush_cache=false` is implemented with `flush_cache=true`. That's the only way I got my NBViewer extension to work: https://github.com/NERSC/clonenotebooks/search?q=flush_cache&unscoped_q=flush_cache

In order to fix this issue we would have to make a backwards incompatible fix to the bug, which seems to be what people want, since having the opposite behavior is counter-intuitive.

I have not had the cycles to devote to maintaining any software projects recently, being focused on my PhD research. I think this could be a pretty quick fix if/when I find the time -- I think I even posted the link to the specific lines of code which are the problem somewhere in this thread or another thread earlier, so if someone else made a PR fixing it which I could just merge, that would be a lot easier for me at least.

**Comment by TMKlautau** [comment]
Having the same problem with this notebook

https://nbviewer.jupyter.org/github/TMKlautau/animal_game_development/blob/master/Animal_game_development.ipynb

anyone found another fix?

**Comment by jiffyclub** [comment]
Looks like some form of this is still an issue, I've been waiting for [this](https://nbviewer.jupyter.org/github/jiffyclub/scipy-2020-intro-to-python/blob/main/Playing%20with%20Blocks.ipynb) notebook view to get refreshed for a couple of hours now. No combination of `flush_cache` flags or browser cache clearing seems to be helping. I get the same result for new browsers and incognito windows.

**Comment by dealmeidavf** [comment]
Same problem here. Notebook rendered by NBviewer is several days old and doesn’t update with or without the `flush_cache` flag.

**Comment by allefeld** [comment]
me too

**Comment by quickgrid** [comment]
Facing same problem. It is showing old version of notebooks that I first used in, https://nbviewer.jupyter.org/. Also one of my notebooks name had comma in it and it showed 400 error. But after renaming the notebook to keep only alphanumeric chatacters and `_` underscore it still shows 400 error.

```
400 : Bad Request
{'type': 'string'} is not valid under any of the given schemas Failed validating 'oneOf' in execute_result['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']: On instance['cells'][39]['outputs'][1]['data']['application/vnd.google.colaboratory.intrinsic+json']: {'type': 'string'}
```

**Comment by cbrnr** [comment]
Unfortunately this problem still exists. My notebooks are not updated (e.g. [this notebook](https://nbviewer.jupyter.org/github/cbrnr/python_intro/blob/master/04/4%20-%20Funktionen.ipynb?flush_cache=true)), sometimes it takes a week until the new versions are rendered. It also seems like this code isn't wrong as some people have indicated:

https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/base.py#L537

Here, `False` is just the default value if the argument `flush_cache` does not exists, and the condition is only fulfilled if `flush_cache` is `True`. So the problem must be somewhere else.

@minrk @krinsman do you have any additional ideas where to look? I'm afraid nbviewer is unusable in its current state, and it would be a pity if people had to look for alternatives because this is such a nice project!

**Comment by maskrove** [comment]
> Unfortunately this problem still exists. My notebooks are not updated (e.g. [this notebook](https://nbviewer.jupyter.org/github/cbrnr/python_intro/blob/master/04/4%20-%20Funktionen.ipynb?flush_cache=true)), sometimes it takes a week until the new versions are rendered. It also seems like this code isn't wrong as some people have indicated:
> 
> https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/base.py#L537
> 
> Here, `False` is just the default value if the argument `flush_cache` does not exist, but the condition is only fulfilled if `flush_cache` is `True`. So the problem must be somewhere else.
> 
> @minrk @krinsman do you have any additional ideas where to look? I'm afraid nbviewer is unusable in its current state, and it would be a pity if people had to look for alternatives because this is such a nice project!

I have exactly the same problem, with the simplest of notebooks.
I have to agree with the sentiment that nbviewer is not usable in this state.

**Comment by cbrnr** [comment]
@maskrove eventually the notebooks will show the latest version, but currently this might happen within an hour or within several days. The problem is that `flush_cache=True` stopped working at some point, which could be used to immediately force the latest notebook version. So it seems you got lucky 😄!

**Comment by djinnome** [comment]
It is even weirder for me.  Nbviewer was not updating the latest version, but now nbviewer is reverting to an even older version than it was before! What is going on?  It would be really nice if that flush_cache option actually worked!

**Comment by jbcaillau** [comment]
Hi,

Note the same issue months ago. Seems that the cache problem remains. Pity, given that nbviewer does otherwise a great job. Anyone in charge around?

**Comment by limegimlet** [comment]
I too am having this problem. While I see my notebook rendered in github here:

https://github.com/limegimlet/covid19/blob/master/dec15_targets.ipynb

I cannot navigate to this notebook on nbviewer, nor does pasting the link above work. 

Oddly enough, I was able to view a similar notebook yesterday, but then was unable to view the subsequent versions today. So I created this new notebook in the hopes that at least the initial commit would be visible. Alas no luck!

**Comment by multinetlab** [comment]
I'm having the same issue here! commited a new version to my repo but nbviewer won't change!

**Comment by KlukvaMors** [comment]
Im having the same problem:(

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/updating-binder-from-changes-on-github/7731/1

**Comment by bryevdv** [comment]
@meeseeksmachine I don't think that is the same issue. That Discourse post regards live running notebooks on binder. I've never experienced any issue with binder notebooks running. Regardless, this issue is about purely *static* (not live) notebooks on nbviewer, which is completely separate from binder. They don't have anything in common.

**Comment by babycamel** [comment]
I have the same problem with nbviewer not regularly refreshing the cache to the latest version on github. in addition the download button on nbviewer no longer works the way it used to.nbviewer seems to have some maintenance issues.

**Comment by Fkaule** [comment]
having the same issue, the nbviewer doesn't show the newest version.  `?flush_cache=false ` or `?flush_cache=true` is not working either

**Comment by subwaymatch** [comment]
Same issue here.

**Comment by MikkoHaavisto** [comment]
I'm seeing different old versions with `flush_cache=false` and `flush_cache=true` and neither is the version currently displayed in GitHub.  

@marcelfg 's solution above works in most cases, but some notebook files are so big they don't render in GitHub even if they could be displayed in nbviewer. In this case, you can't select the link to nbviewer from github.

**Comment by empet** [comment]
After a year this issue persists :(

**Comment by leonheld** [comment]
Still having the same issue. @marcelfg's workaround worked fine for me (using the permalink), although this doesn't seem to be expected behaviour.

**Comment by DocEpsilon** [comment]
me too

**Comment by Gkchandora** [comment]
I am also facing the same issues ! 
1) Added files to existing gist and nbviewer is not showing new files .
2) Deleted the gist, even though nbviewer is rendering the files of gist.

**Comment by bjornarfjelldal** [comment]
Can confirm this is stil an issue as well. Would be really glad to see it resolved :)

**Comment by LeahShl** [comment]
Had the same issue today. adding `?flush_cache=True` solved it. It's case sensitive. Didn't work with `?flush_cache=true` or `?flush_cache=false`.

**Comment by mjturtora** [comment]
:(

**Comment by mjturtora** [comment]
I was having a similar problem so I added "pip install plotly" as cell one even though it seems redundant. NBviewer then took minutes to load but it worked. It also "updated" immediately instead of taking hours for the change to show up. Here is my notebook in NBviewer:

[Notebook in NBviewer](https://nbviewer.org/github/mjturtora/beer/blob/master/Beer.ipynb)

**Comment by BrainAnnex** [comment]
**FIX FOUND!**  (at least works for me...)

Changing the file I have at the top level in my project, `environment.yml` , did the trick for me :)

It's a great file to tell nbviewer exactly what you want.  For example, here's what I have in mine:

```
dependencies:
  - python=3.8
  - numpy==1.22.4
  - pytest==6.2.5
  - jupyterlab==3.4.4
  - ipywidgets==7.7.1
  - jupyter-dash==0.4.2
  - matplotlib==3.5.2
  - plotly==5.9.0
  - pandas==1.4.3
  - scipy==1.9.1
```

If you want to see it in action, check out https://mybinder.org/v2/gh/BrainAnnex/life123/main

**Beware** though: if you use an `environment.yml` file, then your `requirements.txt` (used by my IDE, PyCharm) will get ignored by NBviewer ... and you may have to maintain both files.  I had added scipy to my `requirements.txt` file, but forgot to also add it to `environment.yml` file - and then was going crazy trying to figure out why NBviewer was using a cache!

**Comment by joecerniglia** [comment]
I had been typing ?flush_cache=True at the end of the URL. That didn't work. Then I tried ?flush_cache=true, lowercase true. That worked. It may be cargo cult science and the update was timed to happen at that moment, but it worked.

**Comment by MK8BK** [comment]
still having this issue, no Upper/Lower case `?flush_cache=True` does the trick
seems like nbviewer caches too many times

**Comment by CArdilouze** [comment]
In my case, typing the following did not work : ?flush_cache=True , ?flush_cache=true and ?flush_cache=false
BUT, for some odd reason, typing ?flush_cache=False  (uppercase F)  did the trick to update nbviewer.

**Comment by kubark42** [comment]
No combination of `?flush_cache=True`, `?flush_cache=true`, `?flush_cache=false`, or `?flush_cache=False` worked.

Since this has been going on for almost three years now, it looks like it might be a very deep problem. Could we get a button to force a refresh so there's a workaround until this gets a chance to be root-caused?

**Comment by dirkroorda** [comment]
A full night has gone, and NBviewer refuses stubbornly to show the latest version of my notebook on GitHub. I have tried all suggestions found in this thread, except fiddling with .env files.
I have encountered this problem all those years, and it has turned into a bad feeling wrt. to NBviewer: whenever I fix some last typos in an already rendered notebook, I know that my audience will not see them in time.

Unfortunately, NBviewer is the only option, because my notebooks do not render well in GitHub, because of the HTML `<details>` element en because of not listening to the CSS in my notebooks.

Experience taught me that in the end the notebooks will be rendered correctly on NBviewer, but it takes an unpredictable amount of time.

And the issue has cost me an unreasonable amount of time.

Someone has to go into the deep and fix this!

**Comment by bryevdv** [comment]
> Someone has to go into the deep and fix this!

@dirkroorda in fact no one has to do anything&mdash;such is the nature of volunteer Open Source. Personally, I'm not sure whether NBViewer, *the free service*, is actively maintained any longer. Regardless, I do think there are other potential options, that perhaps you have not have considered:

* You could `nbconvert` your notebooks manually yourself, and host the resulting HTML output yourself
* You can (I believe) run your own NBViewer service on your own server. Presumably without all the extra caching infrastructure that `nbviewer.org` employs, things might go more simply and smoothly
* You could use [Binder](https://mybinder.org) instead, to provide actual live, executable notebooks rather than just static renders

The last option is what we ultimately switched to for our project tutorial notebooks, for instance. Live notebooks ended up being a better UX for tutorials, anyway, but of course YMMV depending on your circumstances.

**Comment by dirkroorda** [comment]
Thanks @bryevdv . Sure, there is no obligation whatsoever for anybody to do something.

I did consider all the alternatives you mentioned, but still the current nbviewer has enough advantages to use it.

* I do nbconvert some tutorials myself, but it is not trivial, especially if you convert a  family of tutorials that link to each other. And Nbconverting my older tutorials would break sooo many links.

* Binder: my tutorials download data that have to be ppre-rocessed and cached locally so that next time everything loads quickly. That does not fit nicely on binder.

**Comment by KensingtonOscupant** [comment]
Not a perfect solution either, but at least for the people who have links to NBViewer in their repositories on Github: I have created a [GitHub Action that automatically updates NBViewer links](https://github.com/marketplace/actions/update-nbviewer-links) so that you always have links based on the newest SHA-1 commit hash (=permalink solution that was already mentioned by @marcelfg). This way, the newest version of your notebook is rendered immediately.

**Comment by shoowadoo** [comment]
2025 and still this problem remains.

**Comment by Itz-Agasta** [comment]
2026 and still this problem remains :)
